# fly.toml app configuration file generated for zkfied-frost-testnet on 2025-11-20T21:38:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zkfied-frost-testnet'
primary_region = 'iad'

[build]
  dockerfile = 'services/frost-coordinator/Dockerfile'

[env]
  DATABASE_URL = 'sqlite:///data/zkfied.db'
  IPFS_URL = 'http://127.0.0.1:5001'
  PINATA_JWT = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI4MTdhOTFiMC03NGZmLTQzZGUtOWVlMy1iY2Q1ZWYwNTE0NzMiLCJlbWFpbCI6ImxvY2tlZHByb2RAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiRlJBMSJ9LHsiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiTllDMSJ9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6ImFlMjk5ZWMxNzg2NTNmMmY1ZmVhIiwic2NvcGVkS2V5U2VjcmV0IjoiOGQ2MTQwMWFlMDIwMGU1YjZjNDIxNTM2OTYzMTljOTg1MGQzN2FjYmRiZTJkMzYxNGFmNDcwM2NlMDg2YmYwYiIsImV4cCI6MTc5NjI2Mjg2MX0.yPfp_dcju-zp-s-82_cOClxj8NH9SRy5VpAuqBtttg4'
  LIGHTWALLETD_URL = 'https://testnet.zec.rocks:443'
  PORT = '8080'
  RUST_LOG = 'info'
  ZCASH_NETWORK = 'testnet'
  ZCASH_RPC_PASS = 'public'
  ZCASH_RPC_URL = 'https://dev.zebra.zsa-test.net:443'
  ZCASH_RPC_USER = 'public'

[[mounts]]
  source = 'zkfied_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
